import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ReduxProvider from "@/components/ReduxProvider";
import Header from "@/components/Header";
import ThemeObserver from "@/components/ThemeObserver";
import MobileNav from "@/components/MobileNav";
import Web3Provider from "@/components/Web3Provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#0b0c10] text-black dark:text-white transition-colors duration-200`}
      >
        <Web3Provider>
          <ReduxProvider>
            <ThemeObserver>
              <Header />
              <div className="min-h-screen pb-16 lg:pb-0">{children}</div>
              <MobileNav />
            </ThemeObserver>
          </ReduxProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
